import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'

const font = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body className={font.className}>
        <div className='flex min-h-screen flex-col bg-[#121516] overflow-x-hidden'>
          <main className='flex flex-col flex-1'>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
